#!/usr/bin/env python3

import os, re
#from session import *
from helpers import * 
from scanner.scanner import hwps 
from importlib.machinery import SourceFileLoader

from networking import hwpn
from parser import hwp_parser as hwpp

# Parse arguments
parser = hwpp.create()
args = parser.parse_args()
args.silent = False

##
# Create ~/.hackwp directory if not exists
hackwp_dir = get_hackwp_dir() 
if not os.path.isdir(hackwp_dir):
    perror("~/.hackwp path not found..")
    try:
        os.mkdir(hackwp_dir)
        pinfo("~/.hackwp created")
    except OSError as error:
        perror(error)

# Path to real installation, not symlink
realpath = get_realpath()

##
# Normalize --target
if args.target:
    args.target = args.target.strip("/")

##
# Extract sessions and exit
if args.session_extract:
    n = hwpn(args)
    n.session_extract()
    exit()

##
# Scan target and exit
if args.scan:
    scan_message(args)
    s = hwps(args)
    s.scan();
    exit()

##
# Start attack mode
if args.attack:
    if not args.exploit or not args.target or not args.payload:
        perror("--exploit is required")
        perror("--target is required")
        perror("--payload is required")
        exit()
    surface  = args.attack
    exploit = args.exploit
    exploit_path = realpath + '/exploits/'+surface+'/'+exploit+'/main.py'
    payload_path = realpath + '/payloads/'+args.payload+'/main.py'
    exploit = SourceFileLoader("Exploit Module",exploit_path).load_module()
    payload = SourceFileLoader("Payload Module",payload_path).load_module()

    method = payload_is_compatible(exploit, payload) 
    if not method:
        perror("This payload is not available for this exploit")
        pwarn("Exploit can handle:", exploit.get_methods())
        pwarn("The payload needs", payload.get_methods())
        exit()

    # Override automatic method
    method = args.method if args.method else method

    # Go
    # FIXME: This should be loaded dynamically
    launch_message(exploit, payload, args)
    instructions = payload.get_instructions(method, args)
    iid = False
    for instruction in instructions:
        if method == 'RCE':
            exploit.rce(instruction, args)
        elif method == 'LFI':
            exploit.lfi(instruction, args)
        elif method == 'RFI':
            exploit.rfi(instruction, args)
        elif method == 'SQLe':
            if iid:
                instruction = re.sub('#iid#', iid, instruction)
                iid = False
            res = exploit.sqle(instruction, args)
            if res['iid']:
                iid = res['iid']

        elif method == 'SQLr':
            exploit.sqlr(instruction, args)
    exit()

hwp_ascii()
psuccess("Version:", get_version())

#r = hwpn(args)
#res = r.post(args.target, json={'testing':'test'})
#print(res.text)
